### ISSUE TITLE
Цвет цитат

### ISSUE THREAD

**Issue by igorsaux** [ChaoticOnyx/OnyxForum#94]
Добавить фон для блоков с цитатами чтобы не сливались с остальным текстом.

Как вариант:

```css
blockquote {
    background-color: rgba(0, 0, 0, 0.1);
}
```
